-- Create purchases table
create table
  public.purchases (
    id bigint generated by default as identity not null,
    user_email text null,
    type text null,
    created_at timestamp with time zone null default now(),
    purchase_id text null,
    payload jsonb null,
    github_username text null,
    provider text null,
    constraint purchases_pkey primary key (id)
  ) tablespace pg_default;

-- Create indexes for better performance
CREATE INDEX idx_purchases_created_at ON public.purchases(created_at);
CREATE INDEX idx_purchases_user_email ON public.purchases(user_email);
CREATE INDEX idx_purchases_type ON public.purchases(type);
CREATE INDEX idx_purchases_purchase_id ON public.purchases(purchase_id);
CREATE INDEX idx_purchases_github_username ON public.purchases(github_username);
CREATE INDEX idx_purchases_provider ON public.purchases(provider);
CREATE INDEX idx_purchases_payload ON public.purchases USING gin (payload);

-- Enable Row Level Security
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;